@extends('layouts.app')

@section('title')
	Privacy Policy
@endsection

@section('content')
	@include('layouts.components.navigation.topbarSheet')
	<div class="layout__sheet">
		<h1>Privacy Policy</h1>
		<p>
			Responsible authority in the sense of the data protection laws, in particular the EU data
			protection basic regulation (DSGVO), is Dennis Prudlo.
		</p>

		<h2>Your rights of data subjects</h2>
		<p>You can exercise the following rights at any time using the contact details provided by our data protection officer:</p>
		<ul>
			<li>Information about your data stored with us and their processing (Art. 15 DSGVO</li>
			<li>Correction of incorrect personal data (Art. 16 DSGVO)</li>
			<li>Deletion of your data stored with us (Art. 17 DSGVO)</li>
			<li>Restriction of data processing if we are not yet allowed to delete your data due to legal obligations (Art. 18 DSGVO)</li>
			<li>Objection to the processing of your data by us (Art. 21 DSGVO)</li>
			<li>Data transferability if you have consented to data processing or have concluded a contract with us (Art. 20 DSGVO)</li>
		</ul>
		<p>
			If you have given us your consent, you can revoke it at any time with effect for the future.
			You may at any time file a complaint with a supervisory authority, e.g. the competent supervisory authority of the federal state in which you reside or the authority responsible for us.
			You will find a list of the supervisory authorities (for the non-public sector) with their addresses at <a href="https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html">www.bfdi.bund.de</a>.
		</p>

		<h2>Contact Form</h2>
		<h3>Nature and purpose of the processing</h3>
		<p>
			The data you enter will be stored for the purpose of individual communication with you.
			For this purpose it is necessary to provide a valid e-mail address and your name.
			This is used to assign the query and then answer it.
			The entry of further data is optional.
		</p>

		<h3>Legal basis</h3>
		<p>
			The data entered in the contact form is processed on the basis of a legitimate interest (Art. 6 para. 1 lit. f DSGVO).
			By providing the contact form, we would like to make it easy for you to contact us.
			Your details will be stored for the purpose of processing your enquiry and for possible follow-up questions.
			If you contact us to request an offer, the data entered in the contact form will be processed to carry out pre-contractual measures (Art. 6 para. 1 lit. b DSGVO).
		</p>

		<h3>Receivers</h3>
		<p>The recipients of the data may be order processors.</p>

		<h3>Storage Period</h3>
		<p>
			Data will be deleted at the latest 6 months after processing the request.
			If it comes to a contractual relationship, we are subject to the legal retention periods according to HGB and delete your data after these periods.
		</p>

		<h3>Provision prescribed or required</h3>
		<p>
			The provision of your personal data is voluntary.
			However, we can only process your request if you provide us with your name, e-mail address and the reason for the request.
		</p>

		<h2>Use of Google Analytics</h2>
		<h3>Nature and purpose of the processing</h3>
		<p>
			This website uses Google Analytics, a web analysis service of Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043 USA (hereinafter: "Google").
			Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site.
			The information generated by the cookie about your use of the website will generally be transmitted to and stored by Google on servers in the United States.
			However, due to the activation of IP anonymisation on these web pages, your IP address will be shortened by Google in advance within member states of the European Union or in other contracting states of the Agreement on the European Economic Area.
			Only in exceptional cases will the full IP address be transmitted to and truncated by Google on servers in the United States.
			On behalf of the operator of this website, Google will use this information to evaluate your use of the website, to compile reports on website activity and to provide other services relating to website activity and internet usage to the website operator.
			The IP address transmitted by your browser as part of Google Analytics is not combined with other data from Google.
			The purposes of data processing are to evaluate the use of the website and to compile reports on activities on the website.
			On the basis of the use of the website and the Internet, further associated services are then to be provided.
		</p>

		<h3>Legal basis</h3>
		<p>The data is processed on the basis of the user's consent (Art. 6 para. 1 lit. a DSGVO).</p>

		<h3>Receivers</h3>
		<p>The recipient of the data is Google as the processor. For this purpose, we have concluded the corresponding contract with Google.</p>

		<h3>Storage Period</h3>
		<p>The data will be deleted as soon as they are no longer required for our recording purposes.</p>

		<h3>Third Country Transfer</h3>
		<p>Google processes your data in the USA and has submitted to the EU_US Privacy Shield. <a href="https://www.privacyshield.gov/EU-US-Framework">https://www.privacyshield.gov/EU-US-Framework</a>.</p>

		<h3>Provision prescribed or required</h3>
		<p>The provision of your personal data is voluntary, solely on the basis of your consent. If you prevent access, this may result in functional restrictions on the website.</p>

		<h3>Revocation of consent</h3>
		<p>
			You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.
			You can also prevent Google from collecting the data generated by the cookie and related to your use of the website (including your IP address) and Google from processing this data by downloading and installing the browser plug-in available under the following link: <a href="http://tools.google.com/dlpage/gaoptout?hl=en">Browser Add On to disable Google Analytics</a>.
			In addition to or as an alternative to the browser add-on, you can prevent tracking by Google Analytics on our pages by <a href="https://htwmate.com/privacy">clicking this link</a>.
			An opt-out cookie is installed on your device.
			This will prevent Google Analytics from collecting cookies for this website and this browser in the future as long as the cookie remains installed in your browser.
		</p>

		<h3>Profiling</h3>
		<p>With the help of the tracking tool Google Analytics the behaviour of the visitors of the website can be evaluated and the interests analysed. For this purpose, we create a pseudonymous user profile.</p>

		<h2>Use of script libraries (Google Web Fonts)</h2>
		<h3>Nature and purpose of the processing</h3>
		<p>
			In order to display our content correctly and graphically appealing across browsers, we use "Google Web Fonts" from Google LLC (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; hereinafter "Google") on this website to display fonts.
			The privacy policy of the library operator Google can be found here: <a href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a>
		</p>

		<h3>Legal basis</h3>
		<p>The legal basis for the integration of Google Webfonts and the associated data transfer to Google is your consent (Art. 6 para. 1 lit. a DSGVO).</p>

		<h3>Receivers</h3>
		<p>Calling script libraries or font libraries automatically triggers a connection to the library operator. It is theoretically possible - but currently unclear if and for what purposes - that the operator collects Google data in this case.</p>

		<h3>Storage Period</h3>
		<p>We do not collect any personal data through the integration of Google Web Fonts. More information about Google Web Fonts can be found at <a href="https://developers.google.com/fonts/faq">https://developers.google.com/fonts/faq</a> and Google's privacy statement: <a href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a></p>

		<h3>Third Country Transfer</h3>
		<p>Google processes your data in the USA and has submitted to the EU_US Privacy Shield. <a href="https://www.privacyshield.gov/EU-US-Framework">https://www.privacyshield.gov/EU-US-Framework</a>.</p>

		<h3>Provision prescribed or required</h3>
		<p>The provision of personal data is neither required by law nor by contract. However, without the correct representation of the contents of standard fonts, it cannot be made possible.</p>

		<h3>Revocation of consent</h3>
		<p>The programming language JavaScript is regularly used to display the contents. You can therefore object to data processing by deactivating the execution of JavaScript in your browser or by installing an integration JavaScript blocker. Please note that this may result in functional restrictions on the website.</p>

		<h2>SSL encryption</h2>
		<p>In order to protect the security of your data during transmission, we use state-of-the-art encryption procedures (e.g. SSL) via HTTPS.</p>

		<h2>Changes to our privacy policy</h2>
		<p>We reserve the right to adapt this data protection declaration so that it always corresponds to the current legal requirements or to implement changes to our services in the data protection declaration, e.g. when introducing new services. Your renewed visit will then be subject to the new data protection declaration.</p>

		<h2>Questions to the Data Protection Officer</h2>
		<p>If you have any questions about data protection, please send us an e-mail or contact the person responsible for data protection in our organisation directly.</p>
	</div>
@endsection
